# DAY_2


In [ ]:

import sys
print(f"Python version: {sys.version}")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("✓ Setup OK!")

Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
✓ Setup OK!


# course:Python for everybody-Dr chuck
Ressource:https://www.py4e.com/

# Course Summarry
##HardWare architecture✔
##Python reserved words ✔
##Variables, expressions and statement✔

In [ ]:
#Chapitre1
##sequence
x=5
print(x)
x=x+10
print(x)
##conditionnal
age =2
if(age>=10 ): print("big")
else:print("small")
##Repeated
n=5
while n>0:
    print(n)
    n=n-1
print("end")

5
15
small
5
4
3
2
1
end


# Exercices

In [ ]:
# conditionals structure
Score=35
if Score>35 : print("win")
elif Score<35: print ("lose")
else : print ("égalité")

égalité


In [ ]:
#Sequence runs
age=20
name="SaahLaHouDine"
print({name},{age})
print(f"{name} is {age}")
print ("Et voila....")

{'SaahLaHouDine'} {20}
SaahLaHouDine is 20
Et voila....


# Linear Algebra
Ressource: 3Blue1Brown - Essence of Linear Algebra ✔

chapter5:Three Dimensional linear transformation :✔

chapitre6: Determinant"factor by which a eara increase in space "✔

chapitre7: Inverse matrices, column space and null space✔

# NumPy-Basics

In [ ]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

#1D arrays
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.shape)

#2D arrays
b = np.array([[1,2,3],     [5,6,7]])
print(b)
print(b.shape)
print(a * 2)
print(a + 10)
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(b[0, 0])
print(b[1, 2])
print(b[:, 0])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3]
 [5 6 7]]
(2, 3)
[ 2  4  6  8 10]
[11 12 13 14 15]
15
3.0
5
1
7
[1 5]
